import numpy as np

from gym_gridworlds.gridworld import (
    LEFT, DOWN, RIGHT, UP, STAY, WALL, GOOD, REWARDS, GRIDS, COLORMAP, Color
)
from gym_gridworlds.gridworld import Gridworld

ROCK = WALL
GOAL = GOOD
GRASS = 99
ROAD = 98
SWAMP = 97

COLORMAP[ROCK] = Color.GRAY
COLORMAP[GRASS] = Color.GREEN
COLORMAP[ROAD] = Color.PALE_YELLOW
COLORMAP[SWAMP] = Color.BROWN
COLORMAP[GOAL] = Color.RED

REWARDS[ROCK] = -1.0
REWARDS[GRASS] = -1.0
REWARDS[ROAD] = -0.25
REWARDS[SWAMP] = -2.0
REWARDS[GOAL] = 0

GRIDS["small_field"] = [
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
    [GRASS, ROCK, GRASS, ROCK, GRASS, GRASS, SWAMP, SWAMP, GOAL, ROAD],
    [GRASS, ROCK, GRASS, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROAD],
    [SWAMP, SWAMP, GRASS, ROCK, SWAMP, SWAMP, SWAMP, GRASS, ROCK, ROAD],
    [ROAD, SWAMP, ROCK, ROAD, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROAD],
    [ROAD, GRASS, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, ROAD],
    [ROAD, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, SWAMP, GRASS, ROAD, ROAD],
    [GRASS, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROCK, ROAD, GRASS],
    [GRASS, GRASS, ROCK, ROCK, ROCK, GRASS, ROCK, ROAD, ROAD, GRASS],
    [GRASS, GRASS, GRASS, GRASS, ROCK, ROAD, ROAD, ROAD, GRASS, GRASS],
]

GRIDS["large_field"] = [
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ],
    [GRASS, GRASS, GRASS, GRASS, ROCK, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ROCK, ROCK, ROCK, ROCK, ROCK, ROCK, ROCK, ROCK, ROCK, GRASS, GRASS, GRASS, GRASS, ROAD, ROAD, ],
    [GRASS, GRASS, ROCK, GRASS, GRASS, ROCK, GRASS, GRASS, GRASS, GRASS, ROCK, ROCK, ROCK, ROCK, GRASS, GRASS, GRASS, SWAMP, SWAMP, SWAMP, GRASS, ROCK, ROCK, GRASS, GOAL, GRASS, ROCK, ROAD, ],
    [GRASS, ROCK, GRASS, GRASS, GRASS, GRASS, GRASS, ROCK, ROCK, ROCK, ROCK, ROCK, GRASS, GRASS, GRASS, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, GRASS, GRASS, ROCK, ROCK, ROAD, ],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ROCK, ROCK, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, GRASS, GRASS, GRASS, ROCK, ROAD, ],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, GRASS, GRASS, GRASS, ROCK, ROAD, ],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROCK, GRASS, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, SWAMP, SWAMP, SWAMP, ROCK, ROAD, ],
    [GRASS, GRASS, GRASS, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROCK, ROCK, SWAMP, SWAMP, ROCK, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, SWAMP, ROCK, ROAD, ],
    [GRASS, GRASS, GRASS, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROCK, SWAMP, SWAMP, ROCK, GRASS, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROAD, ROAD, ],
    [GRASS, ROCK, ROCK, ROCK, SWAMP, SWAMP, ROCK, ROCK, ROCK, ROCK, ROCK, ROCK, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, ROCK, GRASS, GRASS, GRASS, GRASS, SWAMP, GRASS, GRASS, ROAD, ROAD, GRASS, ],
    [GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROAD, ROAD, ROAD, ROAD, SWAMP, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, ROCK, ROCK, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ROAD, GRASS, GRASS, ],
    [GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROAD, ROAD, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, SWAMP, ROCK, ROCK, GRASS, GRASS, GRASS, GRASS, GRASS, ROAD, ROAD, GRASS, ],
    [GRASS, ROCK, SWAMP, SWAMP, GRASS, GRASS, ROCK, ROCK, ROCK, SWAMP, ROCK, ROCK, ROCK, ROCK, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROCK, ROCK, GRASS, GRASS, GRASS, GRASS, ROAD, GRASS, ],
    [GRASS, ROCK, ROCK, ROCK, ROCK, ROCK, GRASS, GRASS, ROCK, SWAMP, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, GRASS, ROCK, GRASS, GRASS, GRASS, GRASS, ROAD, GRASS, ],
    [GRASS, GRASS, ROCK, ROCK, ROAD, ROCK, ROCK, ROCK, ROCK, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, GRASS, ROCK, ROCK, GRASS, GRASS, GRASS, ROAD, GRASS, ],
    [GRASS, GRASS, GRASS, ROAD, ROAD, ROAD, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, ROCK, ROCK, GRASS, GRASS, GRASS, GRASS, ROAD, GRASS, ],
    [SWAMP, GRASS, GRASS, GRASS, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, SWAMP, SWAMP, GRASS, ROCK, GRASS, GRASS, GRASS, GRASS, ROAD, GRASS, ],
    [SWAMP, GRASS, GRASS, GRASS, GRASS, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROCK, GRASS, GRASS, GRASS, GRASS, ROAD, ROAD, ],
    [SWAMP, SWAMP, SWAMP, SWAMP, GRASS, GRASS, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, ROCK, ROCK, ROCK, GRASS, ROAD, ROAD, ROAD, GRASS, ],
    [SWAMP, SWAMP, SWAMP, GRASS, GRASS, GRASS, GRASS, SWAMP, SWAMP, SWAMP, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, ROCK, ROCK, ROCK, GRASS, GRASS, ROAD, ROAD, GRASS, ],
    [SWAMP, SWAMP, SWAMP, GRASS, GRASS, GRASS, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, ROAD, ROCK, GRASS, GRASS, GRASS, GRASS, GRASS, ROAD, GRASS, ],
    [SWAMP, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, GRASS, ROAD, ROCK, ROCK, GRASS, GRASS, GRASS, GRASS, ROAD, ROAD, ],
    [GRASS, GRASS, ROCK, ROCK, ROCK, GRASS, GRASS, SWAMP, ROCK, ROCK, ROCK, ROCK, ROCK, SWAMP, SWAMP, SWAMP, GRASS, GRASS, ROAD, ROAD, GRASS, ROCK, ROCK, GRASS, GRASS, GRASS, ROAD, ROAD, ],
    [GRASS, ROCK, ROCK, ROCK, GRASS, GRASS, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, GRASS, GRASS, ROAD, ROAD, GRASS, GRASS, GRASS, ROCK, GRASS, GRASS, GRASS, GRASS, ROAD, ],
    [ROCK, ROCK, GRASS, GRASS, GRASS, SWAMP, ROCK, SWAMP, SWAMP, SWAMP, SWAMP, GRASS, GRASS, SWAMP, GRASS, ROAD, ROAD, ROAD, ROAD, ROAD, GRASS, GRASS, ROCK, ROCK, GRASS, GRASS, GRASS, ROAD, ],
    [ROAD, ROAD, GRASS, GRASS, ROCK, SWAMP, ROCK, SWAMP, SWAMP, SWAMP, GRASS, GRASS, GRASS, ROAD, ROAD, ROAD, ROAD, GRASS, GRASS, ROAD, ROAD, GRASS, GRASS, ROCK, GRASS, GRASS, ROAD, ROAD, ],
    [ROAD, GRASS, GRASS, GRASS, ROCK, SWAMP, ROCK, SWAMP, SWAMP, GRASS, GRASS, ROAD, ROAD, ROAD, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, GRASS, ],
    [GRASS, GRASS, GRASS, GRASS, ROCK, SWAMP, SWAMP, SWAMP, GRASS, ROAD, ROAD, ROAD, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ],
]


class TravelField(Gridworld):
    """
    The agent has to reach the goal while traveling through a field of different tiles:
    GRASS (green) gives -1 reward, SWAMP (brown) gives -2, ROAD (yellow) gives
    -0.25, and ROCK (gray) cannot be walked on.
    The optimal policy goes through ROAD tiles only, but the path is hard to find.
    There are also dead-end roads that may mislead the agent.
    """
